version: '3'

services:
  database:
    image: mysql:5.7
    container_name: db_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./misc/:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  api:
    build: ./backend
    container_name: api_container
    ports:
      - 3001:3001
    depends_on:
      - database
    volumes:
      - ./backend:/app-back
    platform: linux/x86_64

  web:
    build: ./frontend
    container_name: web_container
    ports:
      - 8080:8080
    depends_on:
      - api
    volumes:
      - ./frontend:/app-front
    platform: linux/x86_64
